### PR TITLE
feat: added device search feature in console

### PR DESCRIPTION
**Pull request by vladimirnikolic509**
https://github.com/infinimesh/infinimesh/assets/155978229/554f0c21-aacc-415c-8049-9bd83d9eac2b

### CODE REVIEW

**Comment by slntopp** [comment]
It'd be great to add those search items as tags like in this [example](https://www.naiveui.com/en-US/dark/components/select#tag-input.vue) (although maybe with some colors to distinct the field).

Additionally, it'd be very nice to fix the margins(level by bottom line ig), so that the title (Devices) search and buttons are all on the same level, i'll create the ticket

**Comment by slntopp** [comment]
Also, use round input, so search doesn't stand out from central buttons (like Refresh State)

**Review by slntopp — CHANGES_REQUESTED** [review]
- [ ] Make search box round
- [ ] Create (round) tags from the search tokens with colours
Colours:
-  Green for :enabled and :tags
-  Light Purple for :uuid and :namespace
-  Gray for :title

**Comment by vladimirnikolic509** [comment]
https://github.com/infinimesh/infinimesh/assets/155978229/bfed8ad1-e972-4638-9bb4-d905b763dfa1

**Comment by vladimirnikolic509** [comment]
This comment about the round input and colored tags, the component library doesn't let us to modify. The round input you were talking about is for input not select component. If we want to have it round and the tags to have colors, we need to make our own custom component and it will take some time. WDYT ? @slntopp

**Comment by slntopp** [comment]
Right, i forgot it's `NSelect`..

I suggest that 
1. you create a new issue describing that component (all involved classed, props and all proper tech description), so we can pick it up sometime soon
2. Swap places for Refresh button and search, then we merge this PR

**Comment by slntopp** [comment]
Scratch that, let's make the search wider and put it in the next line
max 90vw, min 640px, about that

**Comment by vladimirnikolic509** [comment]
I have moved it to next line and with larger width which looks good to me. @slntopp 

image

**Comment by SazukinPavel** [comment]
Couldn't we merge the following checks into one like:

if(key === "some" && !device.some.toLowerCase().includes(filterValue)) {
      return false;
}

maybe one time something like this:

if(['title','uuid',....].includes(key) && !device[key].toLowerCase().includes(filterValue)) {
      return false;
}

**Comment by slntopp** [comment]
@SazukinPavel please use Markdown code blocks when posting code

**Comment by slntopp** [comment]
> Changed target branch to `dev`

**Review by SazukinPavel — APPROVED** [review]
Amazing

**Review by slntopp — APPROVED** [review]

**Pull request merged**
